export const PACKAGE = '@kayamo/offline';

export { backoffMs } from './backoff';
export {
  getOfflineDatabaseName,
  getOfflineDb,
  getOfflineScope,
  resetOfflineDb,
  setOfflineUserScope,
  StaleOfflineScopeError,
  type KayaMoDB,
} from './db';
export type {
  LocalAgentMemory,
  LocalAchievementDefinition,
  LocalCocoConversation,
  LocalCocoMessage,
  LocalDailyLoopPreference,
  LocalDailyPlan,
  LocalCompanionEvent,
  LocalCompanionState,
  LocalCosmeticDefinition,
  LocalCosmeticUnlock,
  LocalFood,
  LocalExercise,
  LocalFoodEntry,
  LocalFocusSession,
  LocalEvolutionStage,
  LocalCompass,
  LocalFutureSelf,
  LocalGoal,
  LocalGoalMilestone,
  LocalInboxItem,
  LocalGuidanceSnapshot,
  LocalHabit,
  LocalHabitCompletion,
  LocalMealTemplate,
  LocalPersonalRule,
  LocalJournalEntry,
  LocalBusyBlock,
  LocalPlanningProject,
  LocalTaskMeta,
  LocalTaskDependency,
  LocalTimeBlock,
  LocalMusActionLog,
  LocalActionGrants,
  ScheduleFlexibility,
  ScheduleKind,
  RecurrenceKind,
  AiAccess,
  LocalLifeStoryEntry,
  LocalGroveChapter,
  LocalCircle,
  LocalSocialPrefs,
  LocalRoutine,
  LocalRoutineCompletion,
  LocalServing,
  LocalScripturePassage,
  LocalTask,
  LocalUserAchievement,
  LocalWeightLog,
  LocalWorkout,
  LocalWorkoutPlan,
  LocalWorkoutPlanExercise,
  LocalWorkoutSet,
  LocalRestTimer,
  LocalGymSessionItem,
  LocalGymPlannedSet,
  LocalGymPrefs,
  LocalGymBusyEquipment,
  LocalGymSessionEvent,
  SyncQueueItem,
  SyncCheckpoint,
  SyncableTable,
  OfflineScope,
} from './db';
export {
  applyPullPage,
  compareSyncCursor,
  fetchServerSyncPage,
  pullRemoteChanges,
  type PullPageFetcher,
  type PullStats,
  type SyncCursor,
} from './pull';
export {
  BIDIRECTIONAL_SYNC_REGISTRY,
  LOCAL_ONLY_TABLES,
  type SyncTableSpec,
} from './sync-registry';
export {
  cacheGuidanceSnapshot,
  clearCachedGuidanceSnapshot,
  getCachedGuidanceSnapshot,
} from './guidance';
export {
  completeLocalEveningReflection,
  createLocalFocusSession,
  ensureReviewedScriptureCache,
  finishLocalFocusSession,
  getLocalDailyLoopPreferences,
  getLocalDailyPlan,
  listLocalDailyPlans,
  listLocalFocusHistory,
  listLocalFocusSessions,
  listLocalScripture,
  mergeRemoteDailyPlans,
  mergeRemoteFocusSessions,
  saveLocalDailyLoopPreferences,
  saveLocalDailyPlan,
  startLocalFocusSession,
  tombstoneLocalDailyPlan,
  tombstoneLocalFocusSession,
} from './daily-loop';
export {
  appendLocalCocoMessage,
  createLocalAgentMemory,
  createLocalCocoConversation,
  deleteLocalJournalEntry,
  listLocalAgentMemories,
  listLocalCocoConversations,
  listLocalCocoMessages,
  listLocalJournalEntries,
  mergeRemoteAgentMemories,
  mergeRemoteCocoConversations,
  mergeRemoteCocoMessages,
  rememberJournalEntry,
  saveLocalJournalEntry,
  tombstoneLocalAgentMemory,
  tombstoneLocalCocoConversation,
  tombstoneLocalCocoMessage,
} from './coco';
export {
  createLocalBusyBlock,
  getLocalActionGrants,
  listLocalBusyBlocks,
  saveLocalActionGrant,
  tombstoneLocalBusyBlock,
} from './integrations';
export {
  DEFAULT_TASK_META,
  addLocalDependency,
  createLocalProject,
  createLocalTimeBlock,
  getLocalTaskMeta,
  getLocalTimeBlock,
  listBlockersForTask,
  listLocalProjects,
  listLocalTimeBlocks,
  listLocalTimeBlocksRange,
  listMusActionLog,
  recordMusAction,
  spawnRecurrenceIfNeeded,
  taskIsBlocked,
  tombstoneLocalProject,
  tombstoneLocalTimeBlock,
  undoLatestMusAction,
  updateLocalTimeBlock,
  upsertLocalTaskMeta,
} from './schedule';
export {
  closeLocalGroveChapter,
  createLocalLifeStoryEntry,
  listLocalGroveChapters,
  listLocalLifeStory,
  tombstoneLocalLifeStoryEntry,
} from './archive';
export {
  createLocalCircle,
  getLocalSocialPrefs,
  listLocalCircles,
  saveLocalSocialPrefs,
  tombstoneLocalCircle,
  updateLocalCircle,
} from './circles';
export {
  completeLocalRoutine,
  createLocalRoutine,
  createLocalTask,
  getLocalTask,
  listLocalRoutineCompletions,
  listLocalRoutines,
  listLocalOpenTasks,
  listLocalOverdueTasks,
  listLocalTasks,
  listLocalTasksForDate,
  mergeRemoteRoutineCompletions,
  mergeRemoteRoutines,
  mergeRemoteTasks,
  setLocalTaskCompleted,
  setLocalTaskScheduledFor,
  tombstoneLocalRoutine,
  tombstoneLocalRoutineCompletion,
  tombstoneLocalTask,
  updateLocalTask,
} from './planning';
export {
  completeLocalGoalMilestone,
  completeLocalHabit,
  createLocalCompanionEvent,
  createLocalGoal,
  createLocalGoalMilestone,
  createLocalHabit,
  getLocalCompanionProgression,
  listLocalCompanionEvents,
  listLocalCompanionPresenceDates,
  listLocalGoalMilestones,
  listLocalGoals,
  listLocalHabitCompletions,
  listLocalHabits,
  mergeRemoteCompanionEvents,
  mergeRemoteGoalMilestones,
  mergeRemoteGoals,
  mergeRemoteHabitCompletions,
  mergeRemoteHabits,
  setLocalGoalStatus,
  tombstoneLocalGoal,
  updateLocalGoalMilestone,
} from './journey';
export {
  createLocalInboxItem,
  createLocalPersonalRule,
  getLocalCompass,
  getLocalFutureSelf,
  listLocalInboxItems,
  listLocalPersonalRules,
  processLocalInboxItem,
  mergeRemoteCompasses,
  mergeRemoteFutureSelves,
  mergeRemoteInboxItems,
  mergeRemotePersonalRules,
  saveLocalCompass,
  saveLocalFutureSelf,
  tombstoneLocalInboxItem,
} from './identity';
export {
  cacheFood,
  cacheFoodWithServings,
  evictFoodCacheLru,
  getCachedFood,
  getCachedServings,
  getFoodReadThrough,
  listCachedFoodsWithServings,
  FOOD_CACHE_MAX,
} from './foods-cache';
export {
  useLiveFoodEntries,
  useLiveFoodHistory,
  useLiveMealTemplates,
  useSyncStatus,
} from './hooks';
export {
  instantOnLogicalDate,
  localHourFromInstant,
  logicalDateFromInstant,
  addLogicalCalendarDays,
} from './logical-date';
export { enqueueUpsert, pendingCount } from './queue';
export {
  getSyncStatusSnapshot,
  applySyncQueueItem,
  startSync,
  syncUserOnce,
  syncNow,
  type SyncDeps,
  type SyncStatus,
  type SyncPushHandler,
  type SyncTelemetryEvent,
} from './sync';
export {
  listLocalFoodEntries,
  listLocalFoodHistory,
  listLocalMealTemplates,
  listLocalWeightLogs,
  logFoodEntries,
  logFoodEntry,
  logWeight,
  restoreLocalFoodEntry,
  reviseLocalFoodEntry,
  logWorkout,
  mergeRemoteFoodEntries,
  mergeRemoteMealTemplates,
  mergeRemoteWeightLogs,
  recomputeLocalLogicalDates,
  saveMealTemplate,
  tombstoneLocalFoodEntries,
  tombstoneLocalFoodEntry,
  tombstoneLocalMealTemplate,
  tombstoneLocalWeightLog,
  type LogFoodEntryInput,
} from './writes';
export {
  clearLocalRestTimer,
  completeLocalWorkoutSet,
  extendLocalRestTimer,
  finishLocalWorkout,
  getLocalRestTimer,
  listLocalWorkoutHistory,
  listLocalWorkoutSets,
  mergeRemoteExercises,
  mergeRemoteWorkoutPlanExercises,
  mergeRemoteWorkoutPlans,
  mergeRemoteWorkoutSets,
  mergeRemoteWorkouts,
  saveLocalWorkoutPlan,
  saveLocalWorkoutPlanExercise,
  startLocalRestTimer,
  startLocalWorkout,
  tombstoneLocalWorkout,
  tombstoneLocalWorkoutSet,
} from './training';
export {
  DEFAULT_GYM_REST_SECONDS,
  addGymPlannedSet,
  addGymSessionItem,
  attachGymDraftToWorkout,
  cloneGymSessionToDraft,
  duplicateGymSessionItem,
  getGymPlannedSet,
  getGymSessionItem,
  getLocalGymPrefs,
  gymDraftSessionId,
  listGymBusyEquipment,
  listGymPlannedSets,
  listGymSessionItems,
  recordGymSessionEvent,
  refreshGymItemState,
  removeFutureGymPlannedSet,
  reorderGymSessionItem,
  saveLocalGymPrefs,
  substituteGymSessionItem,
  toggleGymBusyEquipment,
  tombstoneGymSessionItem,
  updateGymPlannedSet,
  updateGymSessionItem,
} from './gym-session';
